#!/bin/bash

while true; do
  OPTION=$(whiptail --title "Main Menu" --menu "Choose an option" 20 50 12 \
  "1" "Add User" \
  "2" "Modify User" \
  "3" "Delete User" \
  "4" "List Users" \
  "5" "Add Group" \
  "6" "Delete Group" \
  "7" "List Groups" \
  "8" "Change Password" \
  "9" "About" \
  "10" "Exit" 3>&1 1>&2 2>&3)

  case $OPTION in
    1)
      USERNAME=$(whiptail --inputbox "Enter the username to add:" 8 39 --title "Add User" 3>&1 1>&2 2>&3)
      PASSWORD=$(whiptail --passwordbox "Enter the password for $USERNAME:" 8 39 --title "Set Password" 3>&1 1>&2 2>&3)
      
      if id "$USERNAME" &>/dev/null; then
        whiptail --msgbox "User $USERNAME already exists!" 8 39 --title "Error"
      else
        useradd "$USERNAME"
        echo "$USERNAME:$PASSWORD" | chpasswd
        whiptail --msgbox "User $USERNAME added successfully!" 8 39 --title "Success"
      fi
      ;;
      
    2)
      USERNAME=$(whiptail --inputbox "Enter the username to modify:" 8 39 --title "Modify User" 3>&1 1>&2 2>&3)
      if id "$USERNAME" &>/dev/null; then
        chage -l "$USERNAME"
        whiptail --msgbox "User $USERNAME modified successfully!" 8 39 --title "Success"
      else
        whiptail --msgbox "User $USERNAME does not exist!" 8 39 --title "Error"
      fi
      ;;
      
    3)
      USERNAME=$(whiptail --inputbox "Enter the username to delete:" 8 39 --title "Delete User" 3>&1 1>&2 2>&3)
      if id "$USERNAME" &>/dev/null; then
        userdel "$USERNAME"
        whiptail --msgbox "User $USERNAME deleted successfully!" 8 39 --title "Success"
      else
        whiptail --msgbox "User $USERNAME does not exist!" 8 39 --title "Error"
      fi
      ;;
      
    4)
      USERS=$(getent passwd | cut -d: -f1)
      whiptail --scrolltext --title "List Users" --msgbox "List of users:\n\n$USERS" 20 70
      ;;
      
    5)
      GROUPNAME=$(whiptail --inputbox "Enter the group name to add:" 8 39 --title "Add Group" 3>&1 1>&2 2>&3)
      if getent group "$GROUPNAME" &>/dev/null; then
        whiptail --msgbox "Group $GROUPNAME already exists!" 8 39 --title "Error"
      else
        groupadd "$GROUPNAME"
        whiptail --msgbox "Group $GROUPNAME added successfully!" 8 39 --title "Success"
      fi
      ;;
      
    6)
      GROUPNAME=$(whiptail --inputbox "Enter the group name to delete:" 8 39 --title "Delete Group" 3>&1 1>&2 2>&3)
      if getent group "$GROUPNAME" &>/dev/null; then
        groupdel "$GROUPNAME"
        whiptail --msgbox "Group $GROUPNAME deleted successfully!" 8 39 --title "Success"
      else
        whiptail --msgbox "Group $GROUPNAME does not exist!" 8 39 --title "Error"
      fi
      ;;
      
    7)
      GROUPS=$(getent group | cut -d: -f1)
      whiptail --msgbox "List of groups:\n$GROUPS" 20 50 --title "List Groups"
      ;;
      
    8)
      USERNAME=$(whiptail --inputbox "Enter the username to change the password:" 8 39 --title "Change Password" 3>&1 1>&2 2>&3)
      if id "$USERNAME" &>/dev/null; then
        PASSWORD=$(whiptail --passwordbox "Enter the new password for $USERNAME:" 8 39 --title "Set Password" 3>&1 1>&2 2>&3)
        echo "$USERNAME:$PASSWORD" | chpasswd
        whiptail --msgbox "Password for $USERNAME changed successfully!" 8 39 --title "Success"
      else
        whiptail --msgbox "User $USERNAME does not exist!" 8 39 --title "Error"
      fi
      ;;
      
    9)
      whiptail --msgbox "This is a user and group management script." 8 39 --title "About"
      ;;
      
    10)
      break
      ;;
      
    *)
      whiptail --msgbox "Invalid option. Please try again." 8 39 --title "Error"
      ;;
  esac
done
